PirateMath/config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  root 'public#home'
  get '/features', to: 'public#features'
  get '/contact', to: 'public#contact'
  resources :users do
    resources :practices
  end

end

PirateMath/app/models/fact.rb
class Fact < ActiveRecord::Base
  has_many :questions
  has_many :practices, through: :questions
end

PirateMath/app/models/practice.rb
class Practice < ActiveRecord::Base
  belongs_to :user
  has_many :questions
  has_many :facts, through: :questions

  def question_hash
    question_hash = {}
    if self.questions.count > 0

      question = self.questions.last
      question_hash[:previous] = {prompt: "#{question.fact.number_1}+#{question.fact.number_2}", answer: question.fact.solution, student_answer: question.answer}
    end
    question_hash[:next] = create_next_question
    question_hash
  end

  def cumulative_practice_data
    return_data = practice_data
    return_data[:facts] = {}
    self.facts.each do |fact|
      return_data[:facts][fact.id] = Hash.new(0)
      fact.questions.where(practice_id: self.id).each do |question|
        if question.answer == fact.solution
          return_data[:facts][fact.id][:correct] += 1
        else
          return_data[:facts][fact.id][:wrong] += 1
        end
      end
    end
    return_data
  end

  def done?
    self.questions.count > 19
  end

  def create_next_question
    fact = Fact.all.sample
    self.questions.create(fact_id: fact.id)
    {prompt: "#{fact.number_1}+#{fact.number_2}"}
  end

  def practice_data
    hash = Hash.new
    hash[:right] = correct_answers self.questions
    hash[:wrong] = wrong_answers self.questions
    hash
  end

  def correct_answers questions
    questions.select{ |question| question.answer == question.fact.solution }.count
  end

  def wrong_answers questions
    questions.select{ |question| question.answer != question.fact.solution }.count
  end
end

PirateMath/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :fact
  belongs_to :practice
end

PirateMath/app/models/user.rb
class User < ActiveRecord::Base
  has_many :practices
  # belongs_to :school

  # validates :username, presence: true, uniqueness: true, length: { in: 3..16 }
  # validates :first_name, presence: true
  # validates :last_name, presence: true

  has_secure_password
end

PirateMath/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    end
  end
  helper_method :current_user

  def authenticate
    return unless params[:sessions][:username] && params[:sessions][:password]
    user = User.find_by(username: params[:sessions][:username])
    return user# if user.password == params[:sessions][:password]
  end

  def log_in user
    session[:user_id] = user.id
  end

  def log_out
    session.clear
  end

  def logged_in?
    !!session[:user_id]
  end
  helper_method :logged_in?
end

PirateMath/app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  def show
     @user = User.find(params[:user_id])
     @practice = Practice.find(params[:id])
     @practice_data = @practice.practice_data
     p @practice_data
     render 'show', :layout => !request.xhr?
  end

  def edit
    @user = User.find_by(id: params[:id])
    @practice = Practice.find_by(id: params[:id])
    @question_data = @practice.question_hash
    render 'edit', :layout => !request.xhr?
  end

  def index
    @user = User.find(params[:user_id])
    if current_user == @user
      render 'index', :layout => !request.xhr?
    else
      log_out
      redirect_to root_path
    end
  end


  def create
    p params
    @user = User.find_by(id: params[:user_id])
    @practice = Practice.create()
    @user.practices << @practice
    redirect_to edit_user_practice_path(@user.id, @practice.id)
  end

  def update
    @user = User.find_by(id: params[:user_id])
    @practice = Practice.find_by(id: params[:id])
    if @practice.done?
      redirect_to user_practice_path
    else
      @question = @practice.questions.last
      @question.update(answer: params[:answer])
      @question_data = @practice.question_hash
      render 'edit', :layout => !request.xhr?
    end
  end

  def destroy
  end
end

PirateMath/app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home
  end

  def features
  end

  def contact
  end
end

PirateMath/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'new', layout: !request.xhr?
  end

  def create
    if @user = authenticate
      log_in @user
      render "users/show", layout: !request.xhr?
    else
      render 'new', layout: !request.xhr?
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

PirateMath/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
    if current_user == @user
      render "show", :layout => !request.xhr?
    else
      log_out
      redirect_to root_path
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      render "show", :layout => !request.xhr?
    else
      render "new", :layout => !request.xhr?
    end
  end

  def new
    render "new", :layout => !request.xhr?
  end

  def edit
    @user = User.find_by(id: params[:id])
    if current_user == @user
      render "edit", :layout => !request.xhr?
    else
      log_out
      redirect_to root_path
    end
  end

  def update
    @user = User.find_by(:id => params[:id])
    if current_user == @user
      @user.update user_params
      if @user.save
        render "show", :layout => !request.xhr?
      else
        render 'edit', :layout => !request.xhr?
      end
    else
      log_out
      redirect_to root_path
    end
  end

  def destroy
    @user = User.find_by(:id => params[:id])
    if current_user == @user
      @user.destroy
    end
    log_out
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :first_name, :last_name, :school_id, :type)
  end
end

PirateMath/app/helpers/application_helper.rb
module ApplicationHelper
end

PirateMath/app/helpers/practices_helper.rb
module PracticesHelper
end

PirateMath/app/helpers/public_helper.rb
module PublicHelper
end

PirateMath/app/helpers/sessions_helper.rb
module SessionsHelper
end

PirateMath/app/helpers/users_helper.rb
module UsersHelper
end

PirateMath/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", :media => "all" %>

  <title>Pirate Math | Math fluency practice with spunk</title>
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>

</head>
<body>
<main class="container-fluid">
  <header>
     <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand navigation" href="/">Pirate Math</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li id="dashboard-button-li" class="private" <% if current_user %> style="display: block;" <% end %>><a class="navigation" id="dashboard" href="/users/<% if current_user %><%=current_user.id%><% end %>">Dashboard</a></li>
            <li id="support-button-li" class="private" <% if current_user %> style="display: block;" <% end %>><a class="navigation" href="/support">Support</a></li>
            <li class="public" <% if current_user %> style="display: none;" <% end %>><a id="features-link" class="navigation" href="/features">Features</a></li>
            <li class="public" <% if current_user %> style="display: none;" <% end %>><a id="contact-link" class="navigation" href="/contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li <% unless current_user %> style="display: none;"<% end %>><%= link_to "Log Out", logout_path, class: "private authentication", id: "logout"%></li>
            <li class="public" <% if current_user %> style="display: none;" <% end %>><a class="navigation" id="sign-up-link" href="/users/new">Sign Up</a></li>
            <li class="public" <% if current_user %> style="display: none;" <% end %>>
              <%= link_to "Sign In", login_path, class: "navigation", id: "sign-in-link" %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  </header>
  <article class="container panel" id="content">
    <%= yield %>
  </article>
</main>
<div id="wave3" class="wave"></div>
<div id="wave2" class="wave"></div>
<div id="pirateship"></div>
<div id="wave1" class="wave"></div>
  <!-- All Javascrip files -->
  <%= javascript_include_tag 'application' %>
  <script src="//www.google.com/jsapi"></script>


</body>
</html>

PirateMath/app/views/practices/create.html.erb
<h1>Practices#create</h1>
<p>Find me in app/views/practices/create.html.erb</p>

PirateMath/app/views/practices/destroy.html.erb
<h1>Practices#destroy</h1>
<p>Find me in app/views/practices/destroy.html.erb</p>

PirateMath/app/views/practices/edit.html.erb
<% success_message = "<h1>Yay, you got it correct! Keep it up!</h1>" %>
<% fail_message = "<h1>Oops, not there yet matee' Keep focused!</h1>" %>
<% if @question_data[:previous] %>
  <% if @question_data[:previous][:answer] == @question_data[:previous][:student_answer] %>
    <% alert_class = "success" %>
    <% alert_message = success_message %>
  <% else %>
    <% alert_class = "fail" %>
    <% alert_message = fail_message %>
  <% end %>
<% else %>
  <% alert_class="" && alert_message = "" %>
<% end %>


<div id="question-viewport">
  <div class="alert <%= alert_class %>"><%= alert_message %></div>
  <%= form_for :question, url: user_practice_path, method: "patch" do |f|%>
    <%= f.label :answer, @question_data[:next][:prompt], id: "question" %>
    <%= f.text_field :answer %>
    <%= f.submit "Answer" %>
  <% end %>
</div>

PirateMath/app/views/practices/index.html.erb
<div id="users_practices">
  <h2>Ready to weather the pirate seas?</h2>
  <%= form_for :practice, url: user_practices_path do |f| %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

PirateMath/app/views/practices/new.html.erb
<h1>Practices#new</h1>
<p>Find me in app/views/practices/new.html.erb</p>

PirateMath/app/views/practices/show.html.erb
<div id="practice-box" class="container rounded">
  <h1 class='practice text-primary'>Good job, <%= @user.first_name %></h1>
  <p class='practice'>You got <%= @practice_data[:right] %> correct!</p>
  <p class='practice'>You got <%= @practice_data[:wrong] %> wrong.</p>
  <%= link_to "done", user_path(@user) %>
</div>

PirateMath/app/views/practices/update.html.erb
<h1>Practices#update</h1>
<p>Find me in app/views/practices/update.html.erb</p>

PirateMath/app/views/users/_form.html.erb
<%= form_for :user, url: users_path, class: "authentication" do |f| %>
  UserName: <%= f.text_field :username %>
  Password: <%= f.password_field :password %>
  First Name: <%= f.text_field :first_name %>
  Last Name: <%= f.text_field :last_name %>
  School Id: <%= f.text_field :school_id %>

  <%= f.submit "Submit" %>
<% end %>

PirateMath/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

PirateMath/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

PirateMath/app/views/users/edit.html.erb
<h1>Edit Your Information</h1>
<%= render 'form' %>

PirateMath/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

PirateMath/app/views/users/new.html.erb
<h1>Sign up for Pirate Math</h1>
<%= render 'form' %>

PirateMath/app/views/users/show.html.erb
<section id="student-dashboard-wrapper">
  <div id="bio-box" class="container rounded">
    <h1 id="<%= @user.id %>" class='bio text-primary'><%= @user.username %></h1>
    <%= link_to 'edit', edit_user_path(@user) %>
    <%= link_to 'Practices', user_practices_path(@user) %>
  </div>
<section>

PirateMath/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>